//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 WindowCustomizeTool.rc 使用
//
#define IDC_MYICON                      2
#define IDD_WINDOWCUSTOMIZETOOL_DIALOG  102
#define IDD_ABOUTBOX                    103
#define IDR_MAINFRAME                   128
#define IDS_STRING_APP_UUID             130
#define IDI_ICON_WINDOWFINDER_0         131
#define IDI_ICON_WINDOWFINDER_1         132
#define IDC_CURSOR_WINDOWFINDER         133
#define IDS_STRING_APP_TITLE            134
#define IDS_STRING_UI_WNDCLASS          135
#define IDS_STRING_UI_TSKICONTEXT       136
#define IDD_DIALOG_WINDOWFINDER1        137
#define IDR_MENU_MAINWND                138
#define IDR_ACCELERATOR_MAINWND         139
#define IDS_STRING_APP_REG_KEYNAME      140
#define IDS_STRING_UI_BACKGCLASS        141
#define IDC_WINDOWFINDER_CAPTION        1623
#define IDC_WINDOWFINDER_CLASS          1624
#define IDC_WINDOWFINDER_HANDLE         1625
#define IDC_WINDOWFINDER_FT             1626
#define ID_MENU_FILE_CLOSE              32774
#define ID_MENU_FILE_EXIT               32775
#define ID_MENU_FILE_NEW                32776
#define ID_MENU_FILE_SAVE_WINDOWLIST    32780
#define ID_MENU_FILE_SAVE_HWNDLIST      32781
#define ID_MENU_EDIT_OPTIONS            32783
#define ID_MENU_WINDOW_NEW              32785
#define ID_MENU_OPTIONS_SETTINGS        32789
#define ID_MENU_OPTIONS_ALWAYSONTOP     32790
#define ID_MENU_OPTIONS_TASKBARICON     32792
#define ID_MENU_HELP_ABOUT              32796
#define ID_MENU_HELP_HELP               32797
#define ID_MENU_OPTIONS_HIDEWHENMINIMID 32798
#define ID_MENU_WINDOW_FIND             32800
#define ID_MENU_WINDOWMANAGER_BTF       32809
#define ID_MENU_WINDOWMANAGER_SWITCHTO  32810
#define ID_MENU_NEW_FRAME_MAINWND       32812
#define ID_MENU_PROCESS_IMAGENAME       32813
#define ID_MENU_PROCESS_PID             32814
#define ID_MENU_PROCESS_TERMINATE       32815
#define ID_MENU_PROCESS_OPENLOCATION    32816
#define ID_MENU_PROCESS_KILLANDDELETE   32817
#define ID_MENU_WINDOWMANAGER_PROPERIES 32819
#define ID_MENU_ALPHA_ADD10             32828
#define ID_MENU_ALPHA_SUB10             32829
#define ID_MENU_ALPHA_ADD               32830
#define ID_MENU_ALPHA_SUB               32831
#define ID_WINDOWMANAGER_MINIMIZE       32834
#define ID_WINDOWMANAGER_MAXIMIZE       32835
#define ID_WINDOWMANAGER_HIDE           32836
#define ID_WINDOWMANAGER_SHOW           32837
#define ID_MENU_WINDOWMANAGER_MAXIMIZE  32838
#define ID_MENU_WINDOWMANAGER_MINIMIZE  32839
#define ID_MENU_WINDOWMANAGER_HIDE      32840
#define ID_MENU_WINDOWMANAGER_SHOW      32841
#define ID_MENU_WINDOWMANAGER_RELOAD    32844
#define ID_MENU_WINDOWMANAGER_SWP       32852
#define ID_MENU_WINDOWMANAGER_ENDTASK   32856
#define ID_MENU_WINDOWMANAGER_DESTROY   32857
#define ID_MENU_WINDOWMANAGER_CLOSE     32858
#define ID_MENU_OPTIONS_RUNATLOGON      32860
//#define ID_EDIT                         32861
//#define ID_ABOUT                        32862
#define ID_MENU_ABOUT                   32863
#define IDC_WINDOWFINDER_HELP           57670
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32864
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
